services:

  postgres:
    image: postgres:15
    container_name: tobok_postgres
    environment:
      POSTGRES_DB: tobok_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BfFQ6EEqRXR36zV4etv4nnLmEC8RVdkLmt69YXv0wWBZ
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: tobok_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: